cas.authn.accept.users:

cas.tgc.secure: false
cas.tgc.same-site-policy: Lax

cas.tgc.crypto.enabled: false
cas.webflow.crypto.enabled: false

cas.server.name: ${app.domain}
cas.server.prefix: ${cas.server.name}
cas.host.name: caspac4j

cas.service-registry.json.location: classpath:/services

server.port: ${app.port}
server.servlet.context-path: /
server.ssl.enabled: false
cas.server.tomcat.httpProxy.enabled: false
cas.server.tomcat.http:
  - enabled: false

cas.authn.oidc.core.issuer:  ${cas.server.name}/oidc
cas.authn.oidc.jwks.file-system.jwks-file: classpath:keystore.jwks

cas.authn.oauth.session-replication.cookie.crypto.signing.key: swjgPFGwYOHh6HJUHFsQ4VtxSZL9lY7ABu0FWDDEDRUMdta0EDi4uUqljTJgUQ7UTC7IMfiWGZVseMERPsl4CQ
cas.authn.oauth.session-replication.cookie.crypto.encryption.key: ybPgaewBWROr1Hsn9vRJdUaD2jv-Kc6kz8mrJP4aDNddTpMn-qIGobl_PeJVgoxOYpC7V31HlX-O61Wglwdz7Q

cas.authn.saml-idp.core.entity-id: ${cas.server.name}/idp
cas.authn.saml-idp.metadata.file-system.location: file:${saml.dir}
